@echo off
echo ========================================
echo  JARVIS V2 - Criador de Instalador
echo ========================================

echo 🔍 Verificando NSIS (Nullsoft Scriptable Install System)...
where makensis >nul 2>nul
if %errorlevel% neq 0 (
    echo ❌ NSIS não encontrado!
    echo 📥 Baixe em: https://nsis.sourceforge.io/Download
    echo 💡 Ou use o instalador portátil (JARVIS-V2-Portable.zip)
    pause
    exit /b 1
)

echo 📝 Criando script NSIS...
echo ; JARVIS V2 Installer Script > jarvis-installer.nsi
echo ; Generated by create-installer.bat >> jarvis-installer.nsi
echo. >> jarvis-installer.nsi
echo !define APP_NAME "JARVIS V2" >> jarvis-installer.nsi
echo !define APP_VERSION "2.0.0" >> jarvis-installer.nsi
echo !define APP_PUBLISHER "JARVIS Team" >> jarvis-installer.nsi
echo !define APP_URL "https://github.com/jarvis-v2" >> jarvis-installer.nsi
echo !define APP_EXE "JARVIS-V2-Launcher.exe" >> jarvis-installer.nsi
echo. >> jarvis-installer.nsi
echo ; Configurações do instalador >> jarvis-installer.nsi
echo Name "${APP_NAME}" >> jarvis-installer.nsi
echo OutFile "JARVIS-V2-Setup.exe" >> jarvis-installer.nsi
echo InstallDir "$PROGRAMFILES\${APP_NAME}" >> jarvis-installer.nsi
echo InstallDirRegKey HKLM "Software\${APP_NAME}" "InstallDir" >> jarvis-installer.nsi
echo RequestExecutionLevel admin >> jarvis-installer.nsi
echo. >> jarvis-installer.nsi
echo ; Interface >> jarvis-installer.nsi
echo !include "MUI2.nsh" >> jarvis-installer.nsi
echo !define MUI_ABORTWARNING >> jarvis-installer.nsi
echo !define MUI_ICON "assets\jarvis-icon.ico" >> jarvis-installer.nsi
echo !define MUI_UNICON "assets\jarvis-icon.ico" >> jarvis-installer.nsi
echo. >> jarvis-installer.nsi
echo ; Páginas >> jarvis-installer.nsi
echo !insertmacro MUI_PAGE_WELCOME >> jarvis-installer.nsi
echo !insertmacro MUI_PAGE_LICENSE "LICENSE.txt" >> jarvis-installer.nsi
echo !insertmacro MUI_PAGE_DIRECTORY >> jarvis-installer.nsi
echo !insertmacro MUI_PAGE_INSTFILES >> jarvis-installer.nsi
echo !insertmacro MUI_PAGE_FINISH >> jarvis-installer.nsi
echo. >> jarvis-installer.nsi
echo !insertmacro MUI_UNPAGE_WELCOME >> jarvis-installer.nsi
echo !insertmacro MUI_UNPAGE_CONFIRM >> jarvis-installer.nsi
echo !insertmacro MUI_UNPAGE_INSTFILES >> jarvis-installer.nsi
echo !insertmacro MUI_UNPAGE_FINISH >> jarvis-installer.nsi
echo. >> jarvis-installer.nsi
echo ; Idiomas >> jarvis-installer.nsi
echo !insertmacro MUI_LANGUAGE "Portuguese" >> jarvis-installer.nsi
echo !insertmacro MUI_LANGUAGE "English" >> jarvis-installer.nsi
echo. >> jarvis-installer.nsi
echo ; Seção de instalação >> jarvis-installer.nsi
echo Section "JARVIS V2" SecMain >> jarvis-installer.nsi
echo   SetOutPath "$INSTDIR" >> jarvis-installer.nsi
echo   File /r "JARVIS-V2-Portable\*.*" >> jarvis-installer.nsi
echo. >> jarvis-installer.nsi
echo   ; Criar atalhos >> jarvis-installer.nsi
echo   CreateDirectory "$SMPROGRAMS\${APP_NAME}" >> jarvis-installer.nsi
echo   CreateShortCut "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk" "$INSTDIR\${APP_EXE}" >> jarvis-installer.nsi
echo   CreateShortCut "$SMPROGRAMS\${APP_NAME}\Desinstalar.lnk" "$INSTDIR\Uninstall.exe" >> jarvis-installer.nsi
echo   CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${APP_EXE}" >> jarvis-installer.nsi
echo. >> jarvis-installer.nsi
echo   ; Registro >> jarvis-installer.nsi
echo   WriteRegStr HKLM "Software\${APP_NAME}" "InstallDir" "$INSTDIR" >> jarvis-installer.nsi
echo   WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayName" "${APP_NAME}" >> jarvis-installer.nsi
echo   WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "UninstallString" "$INSTDIR\Uninstall.exe" >> jarvis-installer.nsi
echo   WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayVersion" "${APP_VERSION}" >> jarvis-installer.nsi
echo   WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "Publisher" "${APP_PUBLISHER}" >> jarvis-installer.nsi
echo   WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "URLInfoAbout" "${APP_URL}" >> jarvis-installer.nsi
echo. >> jarvis-installer.nsi
echo   WriteUninstaller "$INSTDIR\Uninstall.exe" >> jarvis-installer.nsi
echo SectionEnd >> jarvis-installer.nsi
echo. >> jarvis-installer.nsi
echo ; Seção de desinstalação >> jarvis-installer.nsi
echo Section "Uninstall" >> jarvis-installer.nsi
echo   Delete "$DESKTOP\${APP_NAME}.lnk" >> jarvis-installer.nsi
echo   RMDir /r "$SMPROGRAMS\${APP_NAME}" >> jarvis-installer.nsi
echo   RMDir /r "$INSTDIR" >> jarvis-installer.nsi
echo. >> jarvis-installer.nsi
echo   DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" >> jarvis-installer.nsi
echo   DeleteRegKey HKLM "Software\${APP_NAME}" >> jarvis-installer.nsi
echo SectionEnd >> jarvis-installer.nsi

echo 📄 Criando licença...
echo MIT License > LICENSE.txt
echo. >> LICENSE.txt
echo Copyright (c) 2026 JARVIS V2 Team >> LICENSE.txt
echo. >> LICENSE.txt
echo Permission is hereby granted, free of charge, to any person obtaining a copy >> LICENSE.txt
echo of this software and associated documentation files (the "Software"), to deal >> LICENSE.txt
echo in the Software without restriction, including without limitation the rights >> LICENSE.txt
echo to use, copy, modify, merge, publish, distribute, sublicense, and/or sell >> LICENSE.txt
echo copies of the Software, and to permit persons to whom the Software is >> LICENSE.txt
echo furnished to do so, subject to the following conditions: >> LICENSE.txt
echo. >> LICENSE.txt
echo The above copyright notice and this permission notice shall be included in all >> LICENSE.txt
echo copies or substantial portions of the Software. >> LICENSE.txt
echo. >> LICENSE.txt
echo THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR >> LICENSE.txt
echo IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, >> LICENSE.txt
echo FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE >> LICENSE.txt
echo AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER >> LICENSE.txt
echo LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, >> LICENSE.txt
echo OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE >> LICENSE.txt
echo SOFTWARE. >> LICENSE.txt

echo 🏗️ Compilando instalador...
makensis jarvis-installer.nsi

if %errorlevel% neq 0 (
    echo ❌ Erro ao compilar instalador
    pause
    exit /b 1
)

echo ✅ Instalador criado: JARVIS-V2-Setup.exe

echo 🧹 Limpando arquivos temporários...
del jarvis-installer.nsi

echo.
echo ========================================
echo  🎯 Instalador Criado com Sucesso!
echo ========================================
echo.
echo 📁 Arquivos de distribuição:
echo   • JARVIS-V2-Setup.exe (instalador Windows)
echo   • JARVIS-V2-Portable.zip (versão portátil)
echo.
echo 🚀 Para distribuir:
echo   • Instalador: Execute JARVIS-V2-Setup.exe
echo   • Portátil: Descompacte JARVIS-V2-Portable.zip
echo.
echo 💡 O instalador criará atalhos no menu iniciar e área de trabalho
echo.
pause